# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # Label of the runner job
  runner-job:
    # Container must run in Linux based operating system
    runs-on: ubuntu-latest
    # Docker hub image that the container-job executes in
    #container: 
    env:
      APP_DB_USERNAME : postgres
      APP_DB_PASSWORD : postgres
      APP_DB_NAME : postgres
    services:
        postgres:
          image: postgres
          env:
            POSTGRES_HOST_AUTH_METHOD : "trust"    
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 5432:5432
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'
          cache-dependency-path: go_web_services/go.sum
      - name: Install dependencies
        run: |
            go get .
            go get github.com/gorilla/mux@v1.8.1
            go get github.com/lib/pq@v1.10.9


      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v 
