# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.3'
        cache-dependency-path: go_web_services/go.sum
    - name: Install dependencies
      run: |
          go get .
          got get github.com/gorilla/mux@v1.8.1
          got get github.com/lib/pq@v1.10.9

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
